### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by AliYmn** [ganga-devs/ganga#1107]
sudo pip install ganga

<img src="https://i.hizliresim.com/aGbrAB.png"/>

    sudo pip3 install ganga

<img src="https://i.hizliresim.com/5Q163l.png"/>

**Comment by mesmith75** [comment]
The issue seems pretty clear in the first warning and I don't think is related to Ganga. You can try running in a virtualEnv .

**Comment by rob-c** [comment]
@AliYaman This looks like you're using python3 Ganga doesn't support python3 _yet_

**Comment by AliYaman** [comment]
@rob-c I already get the error in both 2.7 and 3 versions...

**Comment by egede** [comment]
You are trying to install Ganga on a Mac which is not something that we have experience with. Nevertheless I would expect it to work.

I think at least I understand the error now. When Ganga is installed, the `setup.py` file is obtaining the version number by importing it from `Ganga/__init__.py`. 

https://github.com/ganga-devs/ganga/blob/0126d980d25e2bb95dcc36e4f8b84c9799700a5f/setup.py#L14

This means that we are effectively importing all of Ganga itself during the installation process. Normally this should be harmless but it is for sure an overkill. In your case, it is making a runtime error look like an installation error which is not helpful.

To sort this out will require some changes in the Jenkins process that builds our release.

**Comment by goi42** [comment]
by the way, I'm experiencing this same problem on my Mac.

**Comment by mesmith75** [comment]
This should be fixed now.

**Comment by goi42** [comment]
It is not fixed for me. The installation completes, but I cannot launch:

```
michaelsmacbookpro:~ michael$ pip install ganga
Collecting ganga
  Downloading ganga-6.7.3.tar.gz (7.7MB)
    100% |████████████████████████████████| 7.7MB 212kB/s 
Collecting ipython==1.2.1 (from ganga)
  Downloading ipython-1.2.1.tar.gz (8.7MB)
    100% |████████████████████████████████| 8.7MB 183kB/s 
Collecting httplib2>=0.8 (from ganga)
  Downloading httplib2-0.10.3.tar.gz (204kB)
    100% |████████████████████████████████| 204kB 3.0MB/s 
Collecting python-gflags>=2.0 (from ganga)
  Downloading python-gflags-3.1.2.tar.gz (52kB)
    100% |████████████████████████████████| 61kB 4.6MB/s 
Collecting google-api-python-client>=1.1 (from ganga)
  Downloading google_api_python_client-1.6.4-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 5.1MB/s 
Collecting stomp.py>=3.1.7 (from ganga)
  Downloading stomp.py-4.1.19.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 4.4MB/s 
Collecting oauth2client<5.0.0dev,>=1.5.0 (from google-api-python-client>=1.1->ganga)
  Downloading oauth2client-4.1.2-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 4.8MB/s 
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client>=1.1->ganga)
  Downloading uritemplate-3.0.0-py2.py3-none-any.whl
Requirement already satisfied: six<2dev,>=1.6.1 in ./anaconda2/lib/python2.7/site-packages (from google-api-python-client>=1.1->ganga)
Collecting docopt>=0.6.2 (from stomp.py>=3.1.7->ganga)
  Downloading docopt-0.6.2.tar.gz
Collecting pyasn1>=0.1.7 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client>=1.1->ganga)
  Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 10.2MB/s 
Collecting pyasn1-modules>=0.0.5 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client>=1.1->ganga)
  Downloading pyasn1_modules-0.2.1-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 376kB/s 
Collecting rsa>=3.1.4 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client>=1.1->ganga)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 326kB/s 
Building wheels for collected packages: ganga, ipython, httplib2, python-gflags, stomp.py, docopt
  Running setup.py bdist_wheel for ganga ... done
  Stored in directory: /Users/michael/Library/Caches/pip/wheels/f8/cc/c6/d54f321acbcb6f6a3baf000045327e7a6d3ba42ed29c630cf0
  Running setup.py bdist_wheel for ipython ... done
  Stored in directory: /Users/michael/Library/Caches/pip/wheels/8f/67/fa/8766db955545116df761690537cb6fbaf0ef5a4ab7a48b817b
  Running setup.py bdist_wheel for httplib2 ... done
  Stored in directory: /Users/michael/Library/Caches/pip/wheels/ca/ac/5f/749651f7925b231103f5316cacca82a487810c22d30f011c0c
  Running setup.py bdist_wheel for python-gflags ... done
  Stored in directory: /Users/michael/Library/Caches/pip/wheels/e8/9e/c1/a54ef14b0aaa051d73277146a27de8addd93a966611a9c4492
  Running setup.py bdist_wheel for stomp.py ... done
  Stored in directory: /Users/michael/Library/Caches/pip/wheels/25/f8/a5/fd083050f49d49a695fa32a5cd3adcd0d41c5bb2832b18f852
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /Users/michael/Library/Caches/pip/wheels/b2/16/5f/c33a2bb5f2dce71205f8e65cbfd05647d79d441282be31fd82
Successfully built ganga ipython httplib2 python-gflags stomp.py docopt
Installing collected packages: ipython, httplib2, python-gflags, pyasn1, pyasn1-modules, rsa, oauth2client, uritemplate, google-api-python-client, docopt, stomp.py, ganga
  Found existing installation: ipython 5.4.1
    Uninstalling ipython-5.4.1:
      Successfully uninstalled ipython-5.4.1
Successfully installed docopt-0.6.2 ganga-6.7.3 google-api-python-client-1.6.4 httplib2-0.10.3 ipython-1.2.1 oauth2client-4.1.2 pyasn1-0.4.2 pyasn1-modules-0.2.1 python-gflags-3.1.2 rsa-3.4.2 stomp.py-4.1.19 uritemplate-3.0.0
michaelsmacbookpro:~ michael$ ganga
Traceback (most recent call last):
  File "/Users/michael/anaconda2/bin/ganga", line 39, in <module>
    standardSetup()
  File "/Users/michael/anaconda2/bin/ganga", line 36, in standardSetup
    from Ganga.PACKAGE import standardSetup
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/Ganga/__init__.py", line 6, in <module>
    from Ganga.Utility.Runtime import allRuntimes
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/Ganga/Utility/Runtime.py", line 24, in <module>
    import Ganga.Utility.logging
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/Ganga/Utility/logging/__init__.py", line 38, in <module>
    config = getConfig("Logging")
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/Ganga/Utility/Config/Config.py", line 177, in getConfig
    raise KeyError('Config section "[{0}]" not found'.format(name))
KeyError: 'Config section "[Logging]" not found'

```

**Comment by goi42** [comment]
Moreover, I think this may have broken my anaconda installation. I haven't installed anything else in the past couple days, and a couple days ago it was fine. Now, when I just try to start a notebook:
```
[I 15:20:51.465 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 15:20:56.537 NotebookApp] Creating new notebook in 
[I 15:20:57.412 NotebookApp] Kernel started: a9eb2dd1-299a-4e16-b731-73c8be3bf3a2
Traceback (most recent call last):
  File "/Users/michael/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/michael/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/IPython/__init__.py", line 43, in <module>
    from .config.loader import Config
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/IPython/config/__init__.py", line 16, in <module>
    from .application import *
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/IPython/config/application.py", line 31, in <module>
    from IPython.config.configurable import SingletonConfigurable
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/IPython/config/configurable.py", line 33, in <module>
    from IPython.utils.text import indent, wrap_paragraphs
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/IPython/utils/text.py", line 28, in <module>
    from IPython.external.path import path
ImportError: cannot import name path
```
It also seems to have hijacked my previously installed pythons. `ipython` now connects to the Anaconda version instead of my system version. `python2` now connects to the Anaconda version instead of my homebrew version. Is this python hijacking expected behavior? The Anaconda ipython doesn't work either:
```
michaelsmacbookpro:~ michael$ ipython
Traceback (most recent call last):
  File "/Users/michael/anaconda2/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/IPython/__init__.py", line 43, in <module>
    from .config.loader import Config
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/IPython/config/__init__.py", line 16, in <module>
    from .application import *
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/IPython/config/application.py", line 31, in <module>
    from IPython.config.configurable import SingletonConfigurable
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/IPython/config/configurable.py", line 33, in <module>
    from IPython.utils.text import indent, wrap_paragraphs
  File "/Users/michael/anaconda2/lib/python2.7/site-packages/IPython/utils/text.py", line 28, in <module>
    from IPython.external.path import path
ImportError: cannot import name path
```
Going to reinstall anaconda and hope for the best...

**Comment by mesmith75** [comment]
What happens inside a virtualenv?

**Comment by goi42** [comment]
My virtualenv seems to have broken when I wasn't looking, but in a Conda environment, I get the same thing.

```
michaelsmacbookpro:testgangainstall michael$ conda create -n forganga python=2.7 anaconda
Fetching package metadata .............
Solving package specifications: y
.

Package plan for installation in environment /Users/michael/anaconda2/envs/forganga:

The following NEW packages will be INSTALLED:

    alabaster:                          0.7.10-py27h9dd7d6e_0     
    anaconda:                           5.0.1-py27he797f56_1      
    anaconda-client:                    1.6.5-py27hc13fba8_0      
    anaconda-navigator:                 1.6.9-py27h103b016_0      
    anaconda-project:                   0.8.0-py27h9e3d455_0      
    appnope:                            0.1.0-py27hb466136_0      
    appscript:                          1.0.1-py27h451298e_1      
    asn1crypto:                         0.22.0-py27h61af4a7_1     
    astroid:                            1.5.3-py27h96f3fd4_0      
    astropy:                            2.0.2-py27h87cc2bd_4      
    babel:                              2.5.0-py27h7311c9e_0      
    backports:                          1.0-py27hb4f9756_1        
    backports.functools_lru_cache:      1.4-py27h2aca819_1        
    backports.shutil_get_terminal_size: 1.0.0-py27hc9115de_2      
    backports_abc:                      0.5-py27h6972548_0        
    beautifulsoup4:                     4.6.0-py27h9416283_1      
    bitarray:                           0.8.1-py27hd5bfd95_0      
    bkcharts:                           0.2-py27haafc882_0        
    blaze:                              0.11.3-py27hb49378a_0     
    bleach:                             2.0.0-py27ha7d1710_0      
    bokeh:                              0.12.10-py27hf91827b_0    
    boto:                               2.48.0-py27hacdd0fd_1     
    bottleneck:                         1.2.1-py27h71f98a3_0      
    bzip2:                              1.0.6-h92991f9_1          
    ca-certificates:                    2017.08.26-ha1e5d58_0     
    cdecimal:                           2.3-py27hf5d9fd9_1        
    certifi:                            2017.7.27.1-py27h482ffc0_0
    cffi:                               1.10.0-py27haac214c_1     
    chardet:                            3.0.4-py27h2842e91_1      
    click:                              6.7-py27h2b86a94_0        
    cloudpickle:                        0.4.0-py27h665dddb_0      
    clyent:                             1.2.2-py27hc0ae608_0      
    colorama:                           0.3.9-py27hbbe92b6_0      
    configparser:                       3.5.0-py27hc7edf1b_0      
    contextlib2:                        0.5.5-py27h9cb85f4_0      
    cryptography:                       2.0.3-py27hab69567_1      
    curl:                               7.55.1-h7601780_3         
    cycler:                             0.10.0-py27hfc73c78_0     
    cython:                             0.26.1-py27h6a053f9_0     
    cytoolz:                            0.8.2-py27ha56cda1_0      
    dask:                               0.15.3-py27h8a1b457_0     
    dask-core:                          0.15.3-py27h6a32bf4_0     
    datashape:                          0.5.4-py27hd6a1745_0      
    dbus:                               1.10.22-h50d9ad6_0        
    decorator:                          4.1.2-py27h9f877ea_0      
    distributed:                        1.19.1-py27h67dd2ec_0     
    docutils:                           0.14-py27h0befae3_0       
    entrypoints:                        0.2.3-py27hd680fb1_2      
    enum34:                             1.1.6-py27hf475452_1      
    et_xmlfile:                         1.0.1-py27hc42f929_0      
    expat:                              2.2.4-h8f26bf8_1          
    fastcache:                          1.0.2-py27hc4635c7_0      
    filelock:                           2.0.12-py27h72fe922_0     
    flask:                              0.12.2-py27h3ac5568_0     
    flask-cors:                         3.0.3-py27h13db576_0      
    freetype:                           2.8-h143eb01_0            
    funcsigs:                           1.0.2-py27hb9f6266_0      
    functools32:                        3.2.3.2-py27h8ceab06_1    
    futures:                            3.1.1-py27hb02a37a_0      
    get_terminal_size:                  1.0.0-h7520d66_0          
    gettext:                            0.19.8.1-hb0f4f8b_2       
    gevent:                             1.2.2-py27hc02608c_0      
    glib:                               2.53.6-ha08cb78_1         
    glob2:                              0.5-py27h2f8fe13_0        
    gmp:                                6.1.2-h4a9834d_0          
    gmpy2:                              2.0.8-py27h7e2fca4_1      
    greenlet:                           0.4.12-py27h081ed54_0     
    grin:                               1.2.1-py27hc43e5f3_1      
    h5py:                               2.7.0-py27h217cc45_1      
    hdf5:                               1.10.1-h6090a45_0         
    heapdict:                           1.0.0-py27hb5e74ad_0      
    html5lib:                           0.999999999-py27hec7e2bc_0
    icu:                                58.2-hea21ae5_0           
    idna:                               2.6-py27hedea723_1        
    imageio:                            2.2.0-py27h37746d9_0      
    imagesize:                          0.7.1-py27h4f7bcc8_0      
    intel-openmp:                       2018.0.0-h68bdfb3_7       
    ipaddress:                          1.0.18-py27h5b9a5b9_0     
    ipykernel:                          4.6.1-py27h1e70a78_0      
    ipython:                            5.4.1-py27h2b3d779_1      
    ipython_genutils:                   0.2.0-py27h8b9a179_0      
    ipywidgets:                         7.0.0-py27h3e52029_0      
    isort:                              4.2.15-py27h5bf637f_0     
    itsdangerous:                       0.24-py27h3948ded_1       
    jbig:                               2.1-h4d881f8_0            
    jdcal:                              1.3-py27hfeaf94f_0        
    jedi:                               0.10.2-py27hbb5dc62_0     
    jinja2:                             2.9.6-py27h92590e2_1      
    jpeg:                               9b-haccd157_1             
    jsonschema:                         2.6.0-py27hd9b497e_0      
    jupyter:                            1.0.0-py27hec63c99_0      
    jupyter_client:                     5.1.0-py27hfaf569a_0      
    jupyter_console:                    5.2.0-py27h9702a86_1      
    jupyter_core:                       4.3.0-py27hd5161ba_0      
    jupyterlab:                         0.27.0-py27h25d4955_2     
    jupyterlab_launcher:                0.4.0-py27he518b91_0      
    lazy-object-proxy:                  1.3.1-py27h712ce3f_0      
    libcxx:                             4.0.1-h579ed51_0          
    libcxxabi:                          4.0.1-hebd6815_0          
    libedit:                            3.1-hb4e282d_0            
    libffi:                             3.2.1-hd939716_3          
    libgfortran:                        3.0.1-h93005f0_2          
    libiconv:                           1.15-h99df5da_5           
    libpng:                             1.6.32-hce72d48_2         
    libsodium:                          1.0.13-hba5e272_2         
    libssh2:                            1.8.0-h1218725_2          
    libtiff:                            4.0.8-h8cd0352_9          
    libxml2:                            2.9.4-hbd0960b_5          
    libxslt:                            1.1.29-h95a2935_5         
    llvmlite:                           0.20.0-py27_0             
    locket:                             0.2.0-py27ha10513d_1      
    lxml:                               4.1.0-py27hcb5f3a6_0      
    lzo:                                2.10-hb6b8854_1           
    markupsafe:                         1.0-py27hd3c86fa_1        
    matplotlib:                         2.1.0-py27h3078195_0      
    mccabe:                             0.6.1-py27h1f69e8d_0      
    mistune:                            0.7.4-py27h1658d75_0      
    mkl:                                2018.0.0-h5ef208c_6       
    mkl-service:                        1.1.2-py27hcba3029_4      
    mpc:                                1.0.3-hc455b36_4          
    mpfr:                               3.1.5-h7fa3772_1          
    mpmath:                             0.19-py27h09cdc99_2       
    msgpack-python:                     0.4.8-py27h635ded4_0      
    multipledispatch:                   0.4.9-py27h10993aa_0      
    navigator-updater:                  0.1.0-py27ha63e0b4_0      
    nbconvert:                          5.3.1-py27h6455e4c_0      
    nbformat:                           4.4.0-py27hddc86d0_0      
    ncurses:                            6.0-ha932d30_1            
    networkx:                           2.0-py27h2503496_0        
    nltk:                               3.2.4-py27h1626047_0      
    nose:                               1.3.7-py27h2ee3cb8_2      
    notebook:                           5.0.0-py27h5f5981d_2      
    numba:                              0.35.0-np113py27_6        
    numexpr:                            2.6.2-py27h99e4b4f_1      
    numpy:                              1.13.3-py27h62f9060_0     
    numpydoc:                           0.7.0-py27h022f19e_0      
    odo:                                0.5.1-py27h992a9f7_0      
    olefile:                            0.44-py27h73ba740_0       
    openpyxl:                           2.4.8-py27h70e7ed9_1      
    openssl:                            1.0.2l-h57f3a61_2         
    packaging:                          16.8-py27h24b219a_0       
    pandas:                             0.20.3-py27h2a3d8ca_2     
    pandoc:                             1.19.2.1-ha5e8f32_1       
    pandocfilters:                      1.4.2-py27hed78c4e_1      
    partd:                              0.3.8-py27h7560dbf_0      
    path.py:                            10.3.1-py27h5e25276_0     
    pathlib2:                           2.3.0-py27he09da1e_0      
    patsy:                              0.4.1-py27h40ed276_0      
    pcre:                               8.41-h29eefc5_0           
    pep8:                               1.7.0-py27hff3397c_0      
    pexpect:                            4.2.1-py27hc4e4961_0      
    pickleshare:                        0.7.4-py27h37e3d41_0      
    pillow:                             4.2.1-py27h2cf1d5f_0      
    pip:                                9.0.1-py27h61def0c_3      
    pkginfo:                            1.4.1-py27ha9221e7_0      
    ply:                                3.10-py27h6279b8a_0       
    prompt_toolkit:                     1.0.15-py27h4a7b9c2_0     
    psutil:                             5.4.0-py27h7076ac6_0      
    ptyprocess:                         0.5.2-py27h70f6364_0      
    py:                                 1.4.34-py27h917aa57_1     
    pyaudio:                            0.2.7-py27h3777516_1      
    pycodestyle:                        2.3.1-py27h5b634e0_0      
    pycosat:                            0.6.2-py27h085d4cc_0      
    pycparser:                          2.18-py27h0d28d88_1       
    pycrypto:                           2.6.1-py27h4efa152_1      
    pycurl:                             7.43.0-py27h398a7fe_3     
    pyflakes:                           1.6.0-py27h4446e76_0      
    pygments:                           2.2.0-py27h1a556bb_0      
    pylint:                             1.7.4-py27hc678664_0      
    pyodbc:                             4.0.17-py27hc9de18c_0     
    pyopenssl:                          17.2.0-py27h732fe57_0     
    pyparsing:                          2.2.0-py27h5bb6aaf_0      
    pyqt:                               5.6.0-py27hf21fe59_6      
    pysocks:                            1.6.7-py27h1cff6a6_1      
    pytables:                           3.4.2-py27ha4551b8_2      
    pytest:                             3.2.1-py27h173df03_1      
    python:                             2.7.14-he768d2d_19        
    python-dateutil:                    2.6.1-py27hd56c96b_1      
    python.app:                         2-py27h84f57d0_6          
    pytz:                               2017.2-py27hb891d23_1     
    pywavelets:                         0.5.2-py27hd99e88a_0      
    pyyaml:                             3.12-py27ha7932d0_1       
    pyzmq:                              16.0.2-py27he61c07e_2     
    qt:                                 5.6.2-h9975529_14         
    qtawesome:                          0.4.4-py27hdeb2f59_0      
    qtconsole:                          4.3.1-py27hdc90b4f_0      
    qtpy:                               1.3.1-py27h39159f8_0      
    readline:                           7.0-h81b24a6_3            
    requests:                           2.18.4-py27h9b2b37c_1     
    rope:                               0.10.5-py27he855d02_0     
    ruamel_yaml:                        0.11.14-py27h31666c4_2    
    scandir:                            1.6-py27h97aa1ee_0        
    scikit-image:                       0.13.0-py27h03e84e1_1     
    scikit-learn:                       0.19.1-py27h9788993_0     
    scipy:                              0.19.1-py27hf01dd8f_3     
    seaborn:                            0.8.0-py27h92884e4_0      
    setuptools:                         36.5.0-py27h2a45cec_0     
    simplegeneric:                      0.8.1-py27h6db5e31_0      
    singledispatch:                     3.4.0.3-py27he22c18d_0    
    sip:                                4.18.1-py27h6300f65_2     
    six:                                1.11.0-py27h7252ba3_1     
    snowballstemmer:                    1.2.1-py27h68ac032_0      
    sortedcollections:                  0.5.3-py27h8094be4_0      
    sortedcontainers:                   1.5.7-py27h322dbbf_0      
    sphinx:                             1.6.3-py27h11269f0_0      
    sphinxcontrib:                      1.0-py27hd2ed746_1        
    sphinxcontrib-websupport:           1.0.1-py27h857890b_1      
    spyder:                             3.2.4-py27h93d9c3e_0      
    sqlalchemy:                         1.1.13-py27hcbc9ed3_0     
    sqlite:                             3.20.1-h900c3b0_1         
    ssl_match_hostname:                 3.5.0.1-py27h8780752_2    
    statsmodels:                        0.8.0-py27h6d68dbf_0      
    subprocess32:                       3.2.7-py27h24b2887_0      
    sympy:                              1.1.1-py27hce55102_0      
    tblib:                              1.3.2-py27ha684fc4_0      
    terminado:                          0.6-py27he40bf16_0        
    testpath:                           0.3.1-py27h72d81a5_0      
    tk:                                 8.6.7-hcdce994_1          
    toolz:                              0.8.2-py27h27228c4_0      
    tornado:                            4.5.2-py27h29aec9e_0      
    traitlets:                          4.3.2-py27hcf08151_0      
    typing:                             3.6.2-py27h646fea0_0      
    unicodecsv:                         0.14.1-py27h170f95c_0     
    unixodbc:                           2.3.4-h4cb4dde_1          
    urllib3:                            1.22-py27hc3787e9_0       
    wcwidth:                            0.1.7-py27h817c265_0      
    webencodings:                       0.5.1-py27h19a9f58_1      
    werkzeug:                           0.12.2-py27hcac71f8_0     
    wheel:                              0.29.0-py27h84bd1c0_1     
    widgetsnbextension:                 3.0.2-py27h56f70de_1      
    wrapt:                              1.10.11-py27hd341262_0    
    xlrd:                               1.1.0-py27hbd41ed1_1      
    xlsxwriter:                         1.0.2-py27h7f1064a_0      
    xlwings:                            0.11.4-py27h4d78f01_0     
    xlwt:                               1.2.0-py27hbeec4ae_0      
    xz:                                 5.2.3-ha24016e_1          
    yaml:                               0.1.7-hff548bb_1          
    zeromq:                             4.2.2-h131e0f7_1          
    zict:                               0.1.3-py27h5fff8b1_0      
    zlib:                               1.2.11-h60db283_1         

Proceed ([y]/n)? 
bzip2-1.0.6-h9 100% |################################| Time: 0:00:00   3.37 MB/s
gettext-0.19.8 100% |################################| Time: 0:00:00  10.12 MB/s
intel-openmp-2 100% |################################| Time: 0:00:00  17.96 MB/s
jbig-2.1-h4d88 100% |################################| Time: 0:00:00  14.76 MB/s
jpeg-9b-haccd1 100% |################################| Time: 0:00:00  18.39 MB/s
libgfortran-3. 100% |################################| Time: 0:00:00  17.67 MB/s
libiconv-1.15- 100% |################################| Time: 0:00:00  20.26 MB/s
libsodium-1.0. 100% |################################| Time: 0:00:00  23.05 MB/s
libssh2-1.8.0- 100% |################################| Time: 0:00:00  23.69 MB/s
lzo-2.10-hb6b8 100% |################################| Time: 0:00:00  22.27 MB/s
pandoc-1.19.2. 100% |################################| Time: 0:00:01  26.19 MB/s
tk-8.6.7-hcdce 100% |################################| Time: 0:00:00  19.99 MB/s
unixodbc-2.3.4 100% |################################| Time: 0:00:00  21.76 MB/s
xz-5.2.3-ha240 100% |################################| Time: 0:00:00  20.32 MB/s
yaml-0.1.7-hff 100% |################################| Time: 0:00:00  19.36 MB/s
zlib-1.2.11-h6 100% |################################| Time: 0:00:00  20.96 MB/s
libpng-1.6.32- 100% |################################| Time: 0:00:00  17.51 MB/s
mkl-2018.0.0-h 100% |################################| Time: 0:00:10  14.95 MB/s
openssl-1.0.2l 100% |################################| Time: 0:00:00  20.51 MB/s
curl-7.55.1-h7 100% |################################| Time: 0:00:00  20.80 MB/s
expat-2.2.4-h8 100% |################################| Time: 0:00:00  18.43 MB/s
freetype-2.8-h 100% |################################| Time: 0:00:00  19.82 MB/s
gmp-6.1.2-h4a9 100% |################################| Time: 0:00:00  18.27 MB/s
hdf5-1.10.1-h6 100% |################################| Time: 0:00:00  21.88 MB/s
icu-58.2-hea21 100% |################################| Time: 0:00:01  23.09 MB/s
libffi-3.2.1-h 100% |################################| Time: 0:00:00  11.88 MB/s
libtiff-4.0.8- 100% |################################| Time: 0:00:00  26.98 MB/s
ncurses-6.0-ha 100% |################################| Time: 0:00:00  19.35 MB/s
pcre-8.41-h29e 100% |################################| Time: 0:00:00  20.50 MB/s
zeromq-4.2.2-h 100% |################################| Time: 0:00:00  27.42 MB/s
glib-2.53.6-ha 100% |################################| Time: 0:00:00  24.09 MB/s
libxml2-2.9.4- 100% |################################| Time: 0:00:00  24.52 MB/s
mpfr-3.1.5-h7f 100% |################################| Time: 0:00:00  27.26 MB/s
readline-7.0-h 100% |################################| Time: 0:00:00  19.97 MB/s
dbus-1.10.22-h 100% |################################| Time: 0:00:00  25.44 MB/s
libxslt-1.1.29 100% |################################| Time: 0:00:00  19.82 MB/s
mpc-1.0.3-hc45 100% |################################| Time: 0:00:00  22.95 MB/s
sqlite-3.20.1- 100% |################################| Time: 0:00:00  24.20 MB/s
python-2.7.14- 100% |################################| Time: 0:00:01   7.02 MB/s
qt-5.6.2-h9975 100% |################################| Time: 0:00:04  16.95 MB/s
alabaster-0.7. 100% |################################| Time: 0:00:00  20.27 MB/s
appnope-0.1.0- 100% |################################| Time: 0:00:00  14.26 MB/s
appscript-1.0. 100% |################################| Time: 0:00:00  13.01 MB/s
asn1crypto-0.2 100% |################################| Time: 0:00:00  17.56 MB/s
backports-1.0- 100% |################################| Time: 0:00:00   2.61 MB/s
backports_abc- 100% |################################| Time: 0:00:00  11.04 MB/s
beautifulsoup4 100% |################################| Time: 0:00:00 437.57 kB/s
bitarray-0.8.1 100% |################################| Time: 0:00:00  18.89 MB/s
boto-2.48.0-py 100% |################################| Time: 0:00:00  13.38 MB/s
cdecimal-2.3-p 100% |################################| Time: 0:00:00  15.34 MB/s
certifi-2017.7 100% |################################| Time: 0:00:00  14.77 MB/s
chardet-3.0.4- 100% |################################| Time: 0:00:00  14.34 MB/s
click-6.7-py27 100% |################################| Time: 0:00:00  19.27 MB/s
cloudpickle-0. 100% |################################| Time: 0:00:00   7.00 MB/s
colorama-0.3.9 100% |################################| Time: 0:00:00   9.25 MB/s
configparser-3 100% |################################| Time: 0:00:00  23.27 MB/s
contextlib2-0. 100% |################################| Time: 0:00:00  20.10 MB/s
dask-core-0.15 100% |################################| Time: 0:00:00  10.50 MB/s
decorator-4.1. 100% |################################| Time: 0:00:00  23.64 MB/s
docutils-0.14- 100% |################################| Time: 0:00:00  11.86 MB/s
enum34-1.1.6-p 100% |################################| Time: 0:00:00  10.40 MB/s
et_xmlfile-1.0 100% |################################| Time: 0:00:00  11.32 MB/s
fastcache-1.0. 100% |################################| Time: 0:00:00  32.83 MB/s
filelock-2.0.1 100% |################################| Time: 0:00:00   6.26 MB/s
funcsigs-1.0.2 100% |################################| Time: 0:00:00  17.95 MB/s
functools32-3. 100% |################################| Time: 0:00:00  13.10 MB/s
futures-3.1.1- 100% |################################| Time: 0:00:00  11.26 MB/s
glob2-0.5-py27 100% |################################| Time: 0:00:00  22.42 MB/s
gmpy2-2.0.8-py 100% |################################| Time: 0:00:00   8.11 MB/s
greenlet-0.4.1 100% |################################| Time: 0:00:00   5.22 MB/s
grin-1.2.1-py2 100% |################################| Time: 0:00:00  21.17 MB/s
heapdict-1.0.0 100% |################################| Time: 0:00:00   5.44 MB/s
idna-2.6-py27h 100% |################################| Time: 0:00:00  18.82 MB/s
imagesize-0.7. 100% |################################| Time: 0:00:00   2.16 MB/s
ipaddress-1.0. 100% |################################| Time: 0:00:00   5.23 MB/s
ipython_genuti 100% |################################| Time: 0:00:00   1.32 MB/s
itsdangerous-0 100% |################################| Time: 0:00:00   4.43 MB/s
jdcal-1.3-py27 100% |################################| Time: 0:00:00   6.40 MB/s
jedi-0.10.2-py 100% |################################| Time: 0:00:00   8.72 MB/s
lazy-object-pr 100% |################################| Time: 0:00:00   7.56 MB/s
locket-0.2.0-p 100% |################################| Time: 0:00:00   2.43 MB/s
lxml-4.1.0-py2 100% |################################| Time: 0:00:00   9.99 MB/s
markupsafe-1.0 100% |################################| Time: 0:00:00  14.13 MB/s
mccabe-0.6.1-p 100% |################################| Time: 0:00:00   6.59 MB/s
mistune-0.7.4- 100% |################################| Time: 0:00:00  10.42 MB/s
mkl-service-1. 100% |################################| Time: 0:00:00   3.21 MB/s
mpmath-0.19-py 100% |################################| Time: 0:00:00  11.27 MB/s
msgpack-python 100% |################################| Time: 0:00:00  11.38 MB/s
multipledispat 100% |################################| Time: 0:00:00   6.54 MB/s
numpy-1.13.3-p 100% |################################| Time: 0:00:00   9.37 MB/s
olefile-0.44-p 100% |################################| Time: 0:00:00   9.48 MB/s
pandocfilters- 100% |################################| Time: 0:00:00   6.01 MB/s
path.py-10.3.1 100% |################################| Time: 0:00:00  11.39 MB/s
pep8-1.7.0-py2 100% |################################| Time: 0:00:00   9.75 MB/s
pkginfo-1.4.1- 100% |################################| Time: 0:00:00   8.65 MB/s
ply-3.10-py27h 100% |################################| Time: 0:00:00  10.53 MB/s
psutil-5.4.0-p 100% |################################| Time: 0:00:00 722.77 kB/s
ptyprocess-0.5 100% |################################| Time: 0:00:00  11.47 MB/s
py-1.4.34-py27 100% |################################| Time: 0:00:00 699.95 kB/s
pyaudio-0.2.7- 100% |################################| Time: 0:00:00  11.28 MB/s
pycodestyle-2. 100% |################################| Time: 0:00:00   2.32 MB/s
pycosat-0.6.2- 100% |################################| Time: 0:00:00   4.77 MB/s
pycparser-2.18 100% |################################| Time: 0:00:00   5.66 MB/s
pycrypto-2.6.1 100% |################################| Time: 0:00:00   7.01 MB/s
pycurl-7.43.0- 100% |################################| Time: 0:00:00   8.62 MB/s
pyodbc-4.0.17- 100% |################################| Time: 0:00:00   8.38 MB/s
pyparsing-2.2. 100% |################################| Time: 0:00:00   9.91 MB/s
pysocks-1.6.7- 100% |################################| Time: 0:00:00  12.17 MB/s
python.app-2-p 100% |################################| Time: 0:00:00   7.54 MB/s
pytz-2017.2-py 100% |################################| Time: 0:00:00   3.20 MB/s
pyyaml-3.12-py 100% |################################| Time: 0:00:00   5.74 MB/s
pyzmq-16.0.2-p 100% |################################| Time: 0:00:00 999.56 kB/s
qtpy-1.3.1-py2 100% |################################| Time: 0:00:00  10.66 MB/s
rope-0.10.5-py 100% |################################| Time: 0:00:00  10.33 MB/s
ruamel_yaml-0. 100% |################################| Time: 0:00:00   8.13 MB/s
scandir-1.6-py 100% |################################| Time: 0:00:00   8.71 MB/s
simplegeneric- 100% |################################| Time: 0:00:00   7.26 MB/s
sip-4.18.1-py2 100% |################################| Time: 0:00:00  12.26 MB/s
six-1.11.0-py2 100% |################################| Time: 0:00:00   6.94 MB/s
snowballstemme 100% |################################| Time: 0:00:00  25.97 MB/s
sortedcontaine 100% |################################| Time: 0:00:00  28.41 MB/s
sphinxcontrib- 100% |################################| Time: 0:00:00   2.32 MB/s
sqlalchemy-1.1 100% |################################| Time: 0:00:00  13.96 MB/s
subprocess32-3 100% |################################| Time: 0:00:00  19.41 MB/s
tblib-1.3.2-py 100% |################################| Time: 0:00:00  13.54 MB/s
toolz-0.8.2-py 100% |################################| Time: 0:00:00  17.30 MB/s
typing-3.6.2-p 100% |################################| Time: 0:00:00  13.73 MB/s
unicodecsv-0.1 100% |################################| Time: 0:00:00   6.40 MB/s
wcwidth-0.1.7- 100% |################################| Time: 0:00:00  11.16 MB/s
webencodings-0 100% |################################| Time: 0:00:00  10.72 MB/s
werkzeug-0.12. 100% |################################| Time: 0:00:00   1.01 MB/s
wrapt-1.10.11- 100% |################################| Time: 0:00:00  16.21 MB/s
xlrd-1.1.0-py2 100% |################################| Time: 0:00:00  15.77 MB/s
xlsxwriter-1.0 100% |################################| Time: 0:00:00  18.55 MB/s
xlwt-1.2.0-py2 100% |################################| Time: 0:00:00  17.90 MB/s
babel-2.5.0-py 100% |################################| Time: 0:00:00  21.83 MB/s
backports.shut 100% |################################| Time: 0:00:00  11.58 MB/s
bottleneck-1.2 100% |################################| Time: 0:00:00   9.64 MB/s
cffi-1.10.0-py 100% |################################| Time: 0:00:00  26.35 MB/s
cycler-0.10.0- 100% |################################| Time: 0:00:00   9.64 MB/s
cytoolz-0.8.2- 100% |################################| Time: 0:00:00  17.95 MB/s
entrypoints-0. 100% |################################| Time: 0:00:00   5.94 MB/s
h5py-2.7.0-py2 100% |################################| Time: 0:00:00  26.77 MB/s
html5lib-0.999 100% |################################| Time: 0:00:00  16.60 MB/s
llvmlite-0.20. 100% |################################| Time: 0:00:00  23.79 MB/s
networkx-2.0-p 100% |################################| Time: 0:00:01   1.77 MB/s
nltk-3.2.4-py2 100% |################################| Time: 0:00:00   2.34 MB/s
numexpr-2.6.2- 100% |################################| Time: 0:00:00  17.39 MB/s
openpyxl-2.4.8 100% |################################| Time: 0:00:00  19.50 MB/s
packaging-16.8 100% |################################| Time: 0:00:00  18.40 MB/s
partd-0.3.8-py 100% |################################| Time: 0:00:00  15.83 MB/s
pathlib2-2.3.0 100% |################################| Time: 0:00:00  29.28 MB/s
pexpect-4.2.1- 100% |################################| Time: 0:00:00  12.42 MB/s
pillow-4.2.1-p 100% |################################| Time: 0:00:00  18.90 MB/s
pyqt-5.6.0-py2 100% |################################| Time: 0:00:00  30.94 MB/s
python-dateuti 100% |################################| Time: 0:00:00  20.63 MB/s
pywavelets-0.5 100% |################################| Time: 0:00:00  36.80 MB/s
qtawesome-0.4. 100% |################################| Time: 0:00:00  22.99 MB/s
scipy-0.19.1-p 100% |################################| Time: 0:00:01   8.11 MB/s
singledispatch 100% |################################| Time: 0:00:00   8.63 MB/s
sortedcollecti 100% |################################| Time: 0:00:00   8.96 MB/s
sphinxcontrib- 100% |################################| Time: 0:00:00  15.05 MB/s
ssl_match_host 100% |################################| Time: 0:00:00   7.07 MB/s
sympy-1.1.1-py 100% |################################| Time: 0:00:00  34.58 MB/s
traitlets-4.3. 100% |################################| Time: 0:00:00  20.79 MB/s
xlwings-0.11.4 100% |################################| Time: 0:00:00  22.35 MB/s
zict-0.1.3-py2 100% |################################| Time: 0:00:00   9.65 MB/s
backports.func 100% |################################| Time: 0:00:00   7.65 MB/s
bleach-2.0.0-p 100% |################################| Time: 0:00:00  15.17 MB/s
clyent-1.2.2-p 100% |################################| Time: 0:00:00   9.81 MB/s
cryptography-2 100% |################################| Time: 0:00:00  25.87 MB/s
cython-0.26.1- 100% |################################| Time: 0:00:00  33.46 MB/s
datashape-0.5. 100% |################################| Time: 0:00:00  18.77 MB/s
get_terminal_s 100% |################################| Time: 0:00:00   1.63 MB/s
gevent-1.2.2-p 100% |################################| Time: 0:00:00  39.19 MB/s
imageio-2.2.0- 100% |################################| Time: 0:00:00  36.86 MB/s
isort-4.2.15-p 100% |################################| Time: 0:00:00  23.13 MB/s
jinja2-2.9.6-p 100% |################################| Time: 0:00:00  23.15 MB/s
jsonschema-2.6 100% |################################| Time: 0:00:00  19.21 MB/s
jupyter_core-4 100% |################################| Time: 0:00:00   5.66 MB/s
navigator-upda 100% |################################| Time: 0:00:00  30.75 MB/s
nose-1.3.7-py2 100% |################################| Time: 0:00:00   1.02 MB/s
numba-0.35.0-n 100% |################################| Time: 0:00:00  27.71 MB/s
pandas-0.20.3- 100% |################################| Time: 0:00:00  29.17 MB/s
patsy-0.4.1-py 100% |################################| Time: 0:00:00  13.51 MB/s
pickleshare-0. 100% |################################| Time: 0:00:00   8.30 MB/s
pyflakes-1.6.0 100% |################################| Time: 0:00:00  11.00 MB/s
pygments-2.2.0 100% |################################| Time: 0:00:00  21.62 MB/s
pytables-3.4.2 100% |################################| Time: 0:00:00  19.27 MB/s
pytest-3.2.1-p 100% |################################| Time: 0:00:00   1.25 MB/s
scikit-learn-0 100% |################################| Time: 0:00:00  21.51 MB/s
testpath-0.3.1 100% |################################| Time: 0:00:00  19.61 MB/s
tornado-4.5.2- 100% |################################| Time: 0:00:00  23.65 MB/s
wheel-0.29.0-p 100% |################################| Time: 0:00:00  15.12 MB/s
astroid-1.5.3- 100% |################################| Time: 0:00:00  19.68 MB/s
astropy-2.0.2- 100% |################################| Time: 0:00:00  21.51 MB/s
bkcharts-0.2-p 100% |################################| Time: 0:00:00  23.13 MB/s
bokeh-0.12.10- 100% |################################| Time: 0:00:00  21.32 MB/s
distributed-1. 100% |################################| Time: 0:00:00  22.59 MB/s
flask-0.12.2-p 100% |################################| Time: 0:00:00 876.88 kB/s
jupyter_client 100% |################################| Time: 0:00:00   3.44 MB/s
matplotlib-2.1 100% |################################| Time: 0:00:00   9.17 MB/s
nbformat-4.4.0 100% |################################| Time: 0:00:00  16.14 MB/s
pip-9.0.1-py27 100% |################################| Time: 0:00:00  14.58 MB/s
prompt_toolkit 100% |################################| Time: 0:00:00  13.82 MB/s
pyopenssl-17.2 100% |################################| Time: 0:00:00  16.49 MB/s
statsmodels-0. 100% |################################| Time: 0:00:00  10.63 MB/s
terminado-0.6- 100% |################################| Time: 0:00:00  10.14 MB/s
dask-0.15.3-py 100% |################################| Time: 0:00:00   2.12 MB/s
flask-cors-3.0 100% |################################| Time: 0:00:00   6.86 MB/s
ipython-5.4.1- 100% |################################| Time: 0:00:00  12.28 MB/s
nbconvert-5.3. 100% |################################| Time: 0:00:00  13.69 MB/s
pylint-1.7.4-p 100% |################################| Time: 0:00:00   2.85 MB/s
seaborn-0.8.0- 100% |################################| Time: 0:00:00   9.86 MB/s
urllib3-1.22-p 100% |################################| Time: 0:00:00   7.46 MB/s
ipykernel-4.6. 100% |################################| Time: 0:00:00  10.57 MB/s
odo-0.5.1-py27 100% |################################| Time: 0:00:00 451.19 kB/s
requests-2.18. 100% |################################| Time: 0:00:00   2.65 MB/s
scikit-image-0 100% |################################| Time: 0:00:02   9.93 MB/s
anaconda-clien 100% |################################| Time: 0:00:00  17.62 MB/s
blaze-0.11.3-p 100% |################################| Time: 0:00:00  14.12 MB/s
jupyter_consol 100% |################################| Time: 0:00:00  14.51 MB/s
notebook-5.0.0 100% |################################| Time: 0:00:00  12.13 MB/s
qtconsole-4.3. 100% |################################| Time: 0:00:00  20.40 MB/s
sphinx-1.6.3-p 100% |################################| Time: 0:00:00  13.00 MB/s
anaconda-proje 100% |################################| Time: 0:00:00  10.59 MB/s
jupyterlab_lau 100% |################################| Time: 0:00:00   3.51 MB/s
numpydoc-0.7.0 100% |################################| Time: 0:00:00   5.34 MB/s
widgetsnbexten 100% |################################| Time: 0:00:00  11.51 MB/s
anaconda-navig 100% |################################| Time: 0:00:00   4.83 MB/s
ipywidgets-7.0 100% |################################| Time: 0:00:00  13.20 MB/s
jupyterlab-0.2 100% |################################| Time: 0:00:01   2.50 MB/s
spyder-3.2.4-p 100% |################################| Time: 0:00:00   7.60 MB/s
jupyter-1.0.0- 100% |################################| Time: 0:00:00   2.40 MB/s
anaconda-5.0.1 100% |################################| Time: 0:00:00   9.36 MB/s
    If this is your first install of dbus, automatically load on login with:
        mkdir -p ~/Library/LaunchAgents
        cp /Users/michael/anaconda2/envs/forganga/org.freedesktop.dbus-session.plist ~/Library/LaunchAgents/
        launchctl load -w ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist

    If this is an upgrade and you already have the org.freedesktop.dbus-session.plist loaded:
        launchctl unload -w ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist
        cp /Users/michael/anaconda2/envs/forganga/org.freedesktop.dbus-session.plist ~/Library/LaunchAgents/
        launchctl load -w ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist

#
# To activate this environment, use:
# > source activate forganga
#
# To deactivate an active environment, use:
# > source deactivate
#

michaelsmacbookpro:testgangainstall michael$ source activate forganga
(forganga) michaelsmacbookpro:testgangainstall michael$ pip install ganga
Collecting ganga
Collecting python-gflags>=2.0 (from ganga)
Collecting google-api-python-client>=1.1 (from ganga)
  Using cached google_api_python_client-1.6.4-py2.py3-none-any.whl
Collecting ipython==1.2.1 (from ganga)
Collecting stomp.py>=3.1.7 (from ganga)
Collecting httplib2>=0.8 (from ganga)
Collecting oauth2client<5.0.0dev,>=1.5.0 (from google-api-python-client>=1.1->ganga)
  Using cached oauth2client-4.1.2-py2.py3-none-any.whl
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client>=1.1->ganga)
  Using cached uritemplate-3.0.0-py2.py3-none-any.whl
Requirement already satisfied: six<2dev,>=1.6.1 in /Users/michael/anaconda2/envs/forganga/lib/python2.7/site-packages (from google-api-python-client>=1.1->ganga)
Collecting docopt>=0.6.2 (from stomp.py>=3.1.7->ganga)
Collecting pyasn1>=0.1.7 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client>=1.1->ganga)
  Using cached pyasn1-0.4.2-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client>=1.1->ganga)
  Using cached pyasn1_modules-0.2.1-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client>=1.1->ganga)
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Installing collected packages: python-gflags, pyasn1, pyasn1-modules, rsa, httplib2, oauth2client, uritemplate, google-api-python-client, ipython, docopt, stomp.py, ganga
  Found existing installation: ipython 5.4.1
    Uninstalling ipython-5.4.1:
      Successfully uninstalled ipython-5.4.1
Successfully installed docopt-0.6.2 ganga-6.7.3 google-api-python-client-1.6.4 httplib2-0.10.3 ipython-1.2.1 oauth2client-4.1.2 pyasn1-0.4.2 pyasn1-modules-0.2.1 python-gflags-3.1.2 rsa-3.4.2 stomp.py-4.1.19 uritemplate-3.0.0
(forganga) michaelsmacbookpro:testgangainstall michael$ ganga
Traceback (most recent call last):
  File "/Users/michael/anaconda2/envs/forganga/bin/ganga", line 39, in <module>
    standardSetup()
  File "/Users/michael/anaconda2/envs/forganga/bin/ganga", line 36, in standardSetup
    from Ganga.PACKAGE import standardSetup
  File "/Users/michael/anaconda2/envs/forganga/lib/python2.7/site-packages/Ganga/__init__.py", line 6, in <module>
    from Ganga.Utility.Runtime import allRuntimes
  File "/Users/michael/anaconda2/envs/forganga/lib/python2.7/site-packages/Ganga/Utility/Runtime.py", line 24, in <module>
    import Ganga.Utility.logging
  File "/Users/michael/anaconda2/envs/forganga/lib/python2.7/site-packages/Ganga/Utility/logging/__init__.py", line 38, in <module>
    config = getConfig("Logging")
  File "/Users/michael/anaconda2/envs/forganga/lib/python2.7/site-packages/Ganga/Utility/Config/Config.py", line 177, in getConfig
    raise KeyError('Config section "[{0}]" not found'.format(name))
KeyError: 'Config section "[Logging]" not found'
(forganga) michaelsmacbookpro:testgangainstall michael$ 
```

**Comment by rob-c** [comment]
@goi42 Are you trying to run Ganga natively in OSX? This is known not to be supported due to problems running on HFS: https://github.com/ganga-devs/ganga/issues/302
Apologies if you're not I was just glancing at your errors.

If you want to run ganga on OSX I'd advise doing so within a centos based docker container as installing on OSX had problems due to ganga having 2 folders with the same case-insensitive name and OSX not supporting case sensitive named folders.

**Comment by goi42** [comment]
Yes, I am running on macOS:
<img width="767" alt="screenshot 2017-12-04 13 02 54" src="https://user-images.githubusercontent.com/15774838/33551970-78d6edf8-d8f3-11e7-9344-5db76306b61b.png">

**Comment by rob-c** [comment]
Then this is about 50% / 50% as to whether this will _ever_ install correctly from when I went back and checked this. git can't cope, tar can't cope and pip and homebrew get even more confused when trying to do case sensitive work on HFS.

Avoiding pointing flaws in filesystems I would just say that it is known and I've mentioned for a while that we don't currently support either OSX or Cygwin/native-windows due to filesystem constraints.
(Everything works on android, the linux on windows stack, docker and everywhere else with a working POSIX filesystem)

The reason why #302 hasn't been implemented has been that this places a large burden on any dev branch significantly out of sync with head due to the scope of the changes.
This was a major reason to wait until about 6.7 as there were a lot of invasive changes in a large PR which would have made rebasing painful.

A long while ago I confirmed that applying the changes I mention in the PR:
```
git mv Ganga GangaCore
find . -name '*.py' -exec sed -i 's/Ganga\./GangaCore\./g' {} \;
find . -name '*.py' -exec sed -i ':a;N;$!ba;s/import Ganga\n/import GangaCore\n/g' {} \;
```
Will give a version of ganga that starts and submits a hello world in native OSX but I never went any further as neither the LHCb stack nor most of the backends that ganga supports have native OSX support.

I'm curious what sort of jobs are you hoping to submit from ganga on OSX?

**Comment by goi42** [comment]
Usually, I am submitting DaVinci jobs. With the way my Docker is set up, I can use it to run DaVinci, but not Ganga; I am very much a neophyte to Docker though, so I'm not saying that wouldn't work for me. This thread seemed to indicate I could install it locally though, which would be my preference.

**Comment by rob-c** [comment]
If you want to run ganga with the lhcb stack you need to run it within a deployed container such as https://hub.docker.com/r/hepsw/cvmfs-lhcb/

From within a container of this flavor you can run DaVinci/ganga or anything else lhcb on OSX with a minimal amount of overhead.
(If you want to get AFS support in docker I suggest bind-mounting an afs mount from OSX into the container otherwise you will need a VM as I don't think there is a nice docker+hep+afs solution given afs is falling out of favor)

Unfortunately if you want ganga to run/monitor LHCb jobs it needs the whole LHCb environment which is only supported within the docker container and I don't think there are plans for native OSX support atm.

**Comment by rob-c** [comment]
https://lhcbqa.web.cern.ch/lhcbqa/674/can-i-run-lhcb-software-on-a-mac?show=679#c679

**Comment by goi42** [comment]
haha yes, thank you Robert. DaVinci works for me within docker via `lb-run`, but I haven't figured out how to run Ganga. It's definitely there as part of cvmfs, but it doesn't run in the normal ways and I haven't taken the time to figure it out. (Steps included here for reference; I know this isn't really what this thread is about.)

```
michaelsmacbookpro:~ michael$ docker run -h dev --privileged -i -t -v /Users/michael/:/root/afolder hepsw/cvmfs-lhcb
2017/12/04 07:36:07 ::: starting cubie-daemon [0.1.20160205]...
2017/12/04 07:36:07 starting 1 go-process...
2017/12/04 07:36:07 running [/etc/cvmfs/run-cvmfs.sh]...
::: cvmfs-config...
::: mounting FUSE...
CernVM-FS: running with credentials 499:497
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /cvmfs/cernvm-prod.cern.ch
CernVM-FS: running with credentials 499:497
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /cvmfs/sft.cern.ch
CernVM-FS: running with credentials 499:497
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /cvmfs/lhcb.cern.ch
::: mounting FUSE... [done]
2017/12/04 07:36:12 running [/etc/cvmfs/run-cvmfs.sh]... [done]
2017/12/04 07:36:12 now running main go-process...
2017/12/04 07:36:12 running [bash]...
::: sourcing LbLogin...
WARNING : using environment variable VO_LHCB_SW_DIR for sharedarea
********************************************************************************
*                          ---- LHCb Login v9r2 ----                           *
*      Building with gcc49 on slc6 x86_64 system (x86_64-slc6-gcc49-opt)       *
********************************************************************************
 --- User_release_area is set to /root/cmtuser
 --- LHCBPROJECTPATH is set to:
    /cvmfs/lhcb.cern.ch/lib/lhcb
    /cvmfs/lhcb.cern.ch/lib/lcg/releases
    /cvmfs/lhcb.cern.ch/lib/lcg/app/releases
    /cvmfs/lhcb.cern.ch/lib/lcg/external
--------------------------------------------------------------------------------
::: sourcing LbLogin... [done]
[root@dev ~]# lb-run DaVinci/latest bash --norc
[DaVinci v42r6p1] ~ # exit
[root@dev ~]# lb-run Ganga/latest ganga
WARNING:lb-run:trying old SetupProject (cannot find project Ganga latest for x86_64-slc6-gcc49-opt in /root/cmtuser:/cvmfs/lhcb.cern.ch/lib/lhcb/LBSCRIPTS/LBSCRIPTS_v9r2/LbRelease/data/DataPkgEnvs:/cvmfs/lhcb.cern.ch/lib/lhcb/LBSCRIPTS/LBSCRIPTS_v9r2/LbUtils/cmake:/root/cmtuser:/cvmfs/lhcb.cern.ch/lib/lhcb:/cvmfs/lhcb.cern.ch/lib/lcg/releases:/cvmfs/lhcb.cern.ch/lib/lcg/app/releases:/cvmfs/lhcb.cern.ch/lib/lcg/external:/cvmfs/lhcb.cern.ch/lib/lhcb:/cvmfs/lhcb.cern.ch/lib/lcg/releases:/cvmfs/lhcb.cern.ch/lib/lcg/app/releases:/cvmfs/lhcb.cern.ch/lib/lcg/external)
ERROR:SetupProject:Cannot find project 'Ganga'
[root@dev ~]# ganga
/cvmfs/lhcb.cern.ch/lib/lhcb/LBSCRIPTS/LBSCRIPTS_v9r2/InstallArea/scripts/ganga: line 19: /cvmfs/ganga.cern.ch/Ganga/install/LATEST/bin/ganga: No such file or directory
/cvmfs/lhcb.cern.ch/lib/lhcb/LBSCRIPTS/LBSCRIPTS_v9r2/InstallArea/scripts/ganga: line 19: exec: /cvmfs/ganga.cern.ch/Ganga/install/LATEST/bin/ganga: cannot execute: No such file or directory
[root@dev ~]# 
```

**Comment by rob-c** [comment]
Ah, OK, This should be relatively simple.
I can suggest the commands to run to make this available. It appears the docker container needs updating to take into account a new cvmfs repo being relied on by LHCb.

I'll try and get back to you on this soon, I'm a little busy right now to start up a new container and go through how to run it. However I think `pip install ganga` _might_ just work, but someone else might be better placed to comment.

**Comment by goi42** [comment]
While I have `pip` installed via Anaconda on my Mac, it does not work within Docker. (It doesn't recognize the `pip` command.) Another thing I haven't taken the time to figure out.

**Comment by goi42** [comment]
Oh, I should also point out that `pip install ganga` mucks with `ipython`. `which ipython` _before_ install reveals Anaconda's version. `which ipython` _after_ install reveals the system version, despite using Anaconda's `pip`. Seems like this would be relevant even for non-Mac builds.

**Comment by mesmith75** [comment]
I think we should look to implement #302 now then? I assume other users (not LHCb) would appreciate it. I don't think there is any major development work ongoing so disruption should be minimal.

**Comment by egede** [comment]
@mesmith75 I think that is in general a good idea. It is not obvious from the above discussion if this will solve all problems but it is another step in the right direction.

**Comment by mesmith75** [comment]
@AliYmn @goi42 Does this work with the latest version of ganga?

**Comment by goi42** [comment]
I haven't attempted to use Ganga on my Mac since my last comment. I'm afraid I cannot check right now as I can't take the time to debug any issues it might cause.

**Comment by mesmith75** [comment]
Closing as stale. I think this should be ok by now...
