### ISSUE TITLE
Corrupt jobs get totalled after ganga exit.

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#164]
Ganga doesn't appear to correctly avoid re-writing 'corrupt' or 'inaccessible' job XML to disk at shutdown.

This is causing bad behaviour of corrupt jobs which will lose data. (i.e. the half-loaded job object appears to be wiping the data which is corrupt from disk rather than leaving the job as untouched).

I'm investigating if this is a trivial fix or not now.

**Comment by egede** [comment]
@rob-c Is this fixed by other PRs?

**Comment by milliams** [comment]
I believe that this was fixed with @drmarkwslater's lock on `safe_save()`.

**Comment by rob-c** [comment]
Nope, this was another issue which is that Ganga will half-load a job and save the half-loaded job over the bad XML which failed to load. This I don't believe has been addressed yet at all.

**Comment by rob-c** [comment]
This is still happening and needs looking into asap. I have a repo which I am switching between branches, one which has a new application object.
I accidentally left the monitoring on and now all objects with the new application not in my repo have just been wiped from disk (ok, maybe I can restore some of them from backups).

This may get annoying until we have ```ganga``` loading all default plugins, but even still this is bad behavior and needs fixing. I suspect not writing a job which is not fully loaded is the correct thing to do regardless of it's dirty status.

**Comment by rob-c** [comment]
This just bit me again during development. I'm going to see if I can find a fix for this now.

**Comment by rob-c** [comment]
Fixed by #351
