### ISSUE TITLE
Singularity Issues on Dirac Job

### ISSUE THREAD

**Issue by asnaylor** [ganga-devs/ganga#1673]
Now i’m using this singularity binary `/cvmfs/oasis.opensciencegrid.org/mis/singularity/current/bin/singularity` I am seeing errors with it building singularity images from dockerhub on some Dirac sites but it works fine on others. This is the error message that i get:
```shell
[34mINFO:   [0m Starting build...
[31mFATAL:  [0m While performing build: conveyor failed to get: error getting username and password: error reading JSON file "/run/user/1000/containers/auth.json": open /run/user/1000/containers/auth.json: permission denied
[34mINFO:   [0m Starting build...
[31mFATAL:  [0m While performing build: conveyor failed to get: error getting username and password: error reading JSON file "/run/user/1000/containers/auth.json": open /run/user/1000/containers/auth.json: permission denied
[34mINFO:   [0m Starting build...
[31mFATAL:  [0m While performing build: conveyor failed to get: error getting username and password: error reading JSON file "/run/user/1000/containers/auth.json": open /run/user/1000/containers/auth.json: permission denied
[31mFATAL:  [0m could not open image /scratch/plt/25355114/singularity_sandbox: failed to retrieve path for /scratch/plt/25355114/singularity_sandbox: lstat /scratch/plt/25355114/singularity_sandbox: no such file or directory
```
I am seeing it fail to build on the `CLOUD.RAL-LCG2.uk` site but it builds fine on the `CLOUD.UKI-LT2-IC-HEP-lz.uk site`.

**Comment by egede** [comment]
I have not seen this before. Reading https://github.com/hpcng/singularity/issues/5068 seems to explain it. So it seems to be a configuration issue on the grid site. It is unclear if we can fix it by simply setting $XDG_RUNTIME_DIR to point to some temporary location before starting singularity, or if something else is required.

**Comment by egede** [comment]
OK, I can replicate this error locally. If I do
```bash
export XDG_RUNTIME_DIR=/run/user/0
```
before starting Ganga (which means poiting this variable to a directory that only root has r/w access to, then I get the error from a local job using singularity
```bash
FATAL:   Unable to handle docker://fedora:latest uri: failed to get SHA of docker://fedora:latest: error getting username and password: error reading JSON file "/run/user/0/containers/auth.json": open /run/user/0/containers/auth.json: permission denied
```

**Comment by egede** [comment]
OK, this should be fixed now. Please try to update #1670 and run again.

**Comment by asnaylor** [comment]
Updated my ganga with #1670 but still having the same error message on `CLOUD.RAL-LCG2.uk`

**Comment by asnaylor** [comment]
Thanks, I pulled the latest PR and this fixes the build issue i was having on `CLOUD.RAL-LCG2.uk`.
