### ISSUE TITLE
Nightly build issues

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#882]
How are we getting a certificate for the nightly tests? Credential problems seem to be the reason for their continued failure.

**Comment by rob-c** [comment]
The VOMS proxy should __NOT__ be being tested in the LHCb env as there is no valid proxy for it to test in this env. The test should be wrapped as depending upon an external proxy. (Which should mean it shouldn't run unless it's a nightly as it depends upon an external VOMS server resource!)

**Comment by mesmith75** [comment]
This is not so much the test of the VOMS proxy - the test of the LHCbDirac functions are failing.

**Comment by rob-c** [comment]
Actually specifically this test will always fail if there is a Dirac Proxy available as the `DiracProxy` code now auto-detects this so that users see it when running the first query against the credential store.
I'll fix the offending line to check that there is _no_ voms proxy and to _not_ create one, rather than checking there are no credentials at all...

**Comment by drmarkwslater** [comment]
Though I don't have an issue with PR #884 per se, I don't think it's going to fix the nightlies as they seem to be failing on `GangaLHCb` tests, specifically because there isn't a `DiracProxy` available:
```
#x1B[0;0mINFO     Passing to Unittest#x1B[0;0m
#x1B[0;33mWARNING  Required credential [DiracProxy(group='lhcb_user')] not found in store#x1B[0;0m
```

I'm not sure if this should be created in the test or if there's something wrong with the creation. I'll have look...

**Comment by drmarkwslater** [comment]
So I've fixed a lot of the problems. Basically, what was happening was that when you run `py.test` in a `virtualenv` it has the shebang set up to point to the python2.6 install from the virtualenv. This means you get python 2.6 irrespective of what's been set up by the previous script. With a bit of messing around I've now got this fixed and that leaves the only failing test to be the one that #884 fixes. In other words, with that merged we should have the nightlies working again 😄

**Comment by egede** [comment]
@drmarkwslater It seems like the nightly is still failing ...

**Comment by rob-c** [comment]
@egede The failure is not due to a test but due to something being run to post-process the tests I think:
```
ImportError: Error importing plugin "Ganga.testlib.fixtures": No module named Ganga.testlib.fixtures
Build step 'Virtualenv Builder' marked build as failure`
```
I think the python env needs updating around a test to allow for whatever it is at this stage to run correctly.

(Looking at this I think it's the source-ing of the LHCb env is losing the local env changes which point to the current ganga install)

**Comment by mesmith75** [comment]
I'm not convinced - The ones I looked at showed a real test failure:
```python
python/Ganga/test/GPI/Credentials/TestCredentials.py:16: AssertionError
```

**Comment by mesmith75** [comment]
It looks to me as if the PYTHONPATH is just missing the install/ganga/python folder.

**Comment by rob-c** [comment]
yes it is, I'm debugging what may be causing this but the folder is dropped after the sourcing of the LHCb env

**Comment by mesmith75** [comment]
SetupGanga doesn't keep it?

**Comment by rob-c** [comment]
No. By design you can't rely on anything surviving the LbLogin followed by running SetupProject (for LHCb externals... we can (should?) drop this step!).
